# Generated by Django 5.0.2 on 2024-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="subject",
            field=models.ManyToManyField(related_name="classes", to="school.subject"),
        ),
    ]
