# Generated by Django 5.0.1 on 2024-02-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classes",
        ),
        migrations.AddField(
            model_name="student",
            name="clas",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="school.class",
            ),
        ),
    ]
