# Generated by Django 5.0.2 on 2024-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_class_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teacher",
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ManyToManyField(to="school.teacher"),
        ),
    ]
