# Generated by Django 5.0.2 on 2024-02-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_subject_teacher_subject_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="school.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="teacher",
            field=models.ManyToManyField(related_name="subjects", to="school.teacher"),
        ),
    ]
