# Generated by Django 5.0.2 on 2024-02-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_class_teacher_alter_subject_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="subject",
        ),
        migrations.AddField(
            model_name="class",
            name="subject",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="school.subject",
            ),
        ),
    ]
